name: less-wifi-hotspot
region: fra  # Frankfurt - closest to Gambia

services:
  - name: payment-backend
    source_dir: backend
    github:
      repo: HexAI-inc/Template19
      branch: main
      deploy_on_push: true
    run_command: node server.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 3001
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: API_BASE_URL
        value: https://hpg-backend-6kzwb.ondigitalocean.app/api/v1
      - key: API_KEY
        value: hexai_pba1qb16rxe
        type: SECRET
      - key: CURRENCY
        value: GMD
      - key: BUSINESS_NAME
        value: LE.SS WiFi
      - key: SUCCESS_URL
        value: https://less-wifi-hotspot-23gu3.ondigitalocean.app/payment-success.html
      - key: ERROR_URL
        value: https://less-wifi-hotspot-23gu3.ondigitalocean.app/error-gambia.html
    routes:
      - path: /api
      - path: /health

static_sites:
  - name: hotspot-frontend
    source_dir: /
    github:
      repo: HexAI-inc/Template19
      branch: main
      deploy_on_push: true
    index_document: login-gambia.html
    error_document: error-gambia.html
    envs:
      - key: BACKEND_URL
        value: ${payment-backend.PUBLIC_URL}
    routes:
      - path: /
